"""initial_schema_five_tables

Revision ID: 32cb25512cff
Revises: 
Create Date: 2026-05-20 19:23:42.455432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32cb25512cff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_name', sa.String(length=100), nullable=False),
    sa.Column('crop_type', sa.String(length=50), nullable=False),
    sa.Column('severity_tier', sa.String(length=20), nullable=False),
    sa.Column('treatment_en', sa.Text(), nullable=False),
    sa.Column('treatment_ne', sa.Text(), nullable=False),
    sa.Column('dosage', sa.String(length=200), nullable=False),
    sa.Column('safety_notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_records_disease_name'), 'treatment_records', ['disease_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('language_pref', sa.String(length=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('diagnosis_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('disease_name', sa.String(length=100), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('severity_level', sa.String(length=20), nullable=True),
    sa.Column('image_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_history_created_at'), 'diagnosis_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_diagnosis_history_disease_name'), 'diagnosis_history', ['disease_name'], unique=False)
    op.create_index('ix_user_disease_time', 'diagnosis_history', ['user_id', 'disease_name', 'created_at'], unique=False)
    op.create_table('treatment_translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('treatment_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=2), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatment_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_treatment_lang_field', 'treatment_translations', ['treatment_id', 'language_code', 'field_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_treatment_lang_field', table_name='treatment_translations')
    op.drop_table('treatment_translations')
    op.drop_index('ix_user_disease_time', table_name='diagnosis_history')
    op.drop_index(op.f('ix_diagnosis_history_disease_name'), table_name='diagnosis_history')
    op.drop_index(op.f('ix_diagnosis_history_created_at'), table_name='diagnosis_history')
    op.drop_table('diagnosis_history')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_treatment_records_disease_name'), table_name='treatment_records')
    op.drop_table('treatment_records')
    # ### end Alembic commands ###
