"""align_schema_to_er_diagram_v2

Revision ID: 4447ec11d413
Revises: 32cb25512cff
Create Date: 2026-05-22 21:52:58.270799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4447ec11d413'
down_revision: Union[str, None] = '32cb25512cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('audit_logs_user_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('diagnosis_history', sa.Column('treatment_id', sa.UUID(), nullable=False))
    op.add_column('diagnosis_history', sa.Column('diagnosed_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_diagnosis_history_created_at', table_name='diagnosis_history')
    op.drop_index('ix_diagnosis_history_disease_name', table_name='diagnosis_history')
    op.drop_index('ix_user_disease_time', table_name='diagnosis_history')
    op.create_index(op.f('ix_diagnosis_history_diagnosed_at'), 'diagnosis_history', ['diagnosed_at'], unique=False)
    op.create_index(op.f('ix_diagnosis_history_treatment_id'), 'diagnosis_history', ['treatment_id'], unique=False)
    op.create_index(op.f('ix_diagnosis_history_user_id'), 'diagnosis_history', ['user_id'], unique=False)
    op.create_index('ix_user_diagnosed_at', 'diagnosis_history', ['user_id', 'diagnosed_at'], unique=False)
    op.drop_constraint('diagnosis_history_user_id_fkey', 'diagnosis_history', type_='foreignkey')
    op.create_foreign_key(None, 'diagnosis_history', 'treatment_records', ['treatment_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'diagnosis_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('diagnosis_history', 'created_at')
    op.drop_column('diagnosis_history', 'disease_name')
    op.add_column('treatment_records', sa.Column('pesticide_name', sa.String(length=100), nullable=False))
    op.add_column('treatment_records', sa.Column('dosage_mild', sa.String(length=200), nullable=False))
    op.add_column('treatment_records', sa.Column('dosage_moderate', sa.String(length=200), nullable=False))
    op.add_column('treatment_records', sa.Column('dosage_severe', sa.String(length=200), nullable=False))
    op.add_column('treatment_records', sa.Column('application_method', sa.String(length=100), nullable=False))
    op.add_column('treatment_records', sa.Column('safety_warning', sa.Text(), nullable=False))
    op.drop_constraint('uq_disease_severity', 'treatment_records', type_='unique')
    op.create_index('ix_disease_crop', 'treatment_records', ['disease_name', 'crop_type'], unique=True)
    op.create_index(op.f('ix_treatment_records_disease_name'), 'treatment_records', ['disease_name'], unique=False)
    op.drop_column('treatment_records', 'treatment_ne')
    op.drop_column('treatment_records', 'safety_notes')
    op.drop_column('treatment_records', 'dosage')
    op.drop_column('treatment_records', 'severity_tier')
    op.drop_column('treatment_records', 'treatment_en')
    op.drop_constraint('treatment_translations_treatment_id_fkey', 'treatment_translations', type_='foreignkey')
    op.create_foreign_key(None, 'treatment_translations', 'treatment_records', ['treatment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'treatment_translations', type_='foreignkey')
    op.create_foreign_key('treatment_translations_treatment_id_fkey', 'treatment_translations', 'treatment_records', ['treatment_id'], ['id'])
    op.add_column('treatment_records', sa.Column('treatment_en', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('treatment_records', sa.Column('severity_tier', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('treatment_records', sa.Column('dosage', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('treatment_records', sa.Column('safety_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('treatment_records', sa.Column('treatment_ne', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_treatment_records_disease_name'), table_name='treatment_records')
    op.drop_index('ix_disease_crop', table_name='treatment_records')
    op.create_unique_constraint('uq_disease_severity', 'treatment_records', ['disease_name', 'severity_tier'])
    op.drop_column('treatment_records', 'safety_warning')
    op.drop_column('treatment_records', 'application_method')
    op.drop_column('treatment_records', 'dosage_severe')
    op.drop_column('treatment_records', 'dosage_moderate')
    op.drop_column('treatment_records', 'dosage_mild')
    op.drop_column('treatment_records', 'pesticide_name')
    op.add_column('diagnosis_history', sa.Column('disease_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('diagnosis_history', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'diagnosis_history', type_='foreignkey')
    op.drop_constraint(None, 'diagnosis_history', type_='foreignkey')
    op.create_foreign_key('diagnosis_history_user_id_fkey', 'diagnosis_history', 'users', ['user_id'], ['id'])
    op.drop_index('ix_user_diagnosed_at', table_name='diagnosis_history')
    op.drop_index(op.f('ix_diagnosis_history_user_id'), table_name='diagnosis_history')
    op.drop_index(op.f('ix_diagnosis_history_treatment_id'), table_name='diagnosis_history')
    op.drop_index(op.f('ix_diagnosis_history_diagnosed_at'), table_name='diagnosis_history')
    op.create_index('ix_user_disease_time', 'diagnosis_history', ['user_id', 'disease_name', 'created_at'], unique=False)
    op.create_index('ix_diagnosis_history_disease_name', 'diagnosis_history', ['disease_name'], unique=False)
    op.create_index('ix_diagnosis_history_created_at', 'diagnosis_history', ['created_at'], unique=False)
    op.drop_column('diagnosis_history', 'diagnosed_at')
    op.drop_column('diagnosis_history', 'treatment_id')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_user_id_fkey', 'audit_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
