"""add_notifications_tables_and_update_users

Revision ID: 5334cf0a3ae5
Revises: 53e569df9656
Create Date: 2026-07-23 21:56:54.222336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5334cf0a3ae5'
down_revision: Union[str, None] = '53e569df9656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notification_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('treatment_reminders_enabled', sa.Boolean(), nullable=False),
    sa.Column('follow_ups_enabled', sa.Boolean(), nullable=False),
    sa.Column('crop_recommendations_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('preferred_notification_hour', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.String(length=30), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('title_ne', sa.String(length=200), nullable=False),
    sa.Column('message_en', sa.Text(), nullable=False),
    sa.Column('message_ne', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_delivered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnosis_history.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_pending', 'notifications', ['scheduled_at', 'sent_at', 'is_active'], unique=False)
    op.create_index('ix_notification_user_unread', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_index(op.f('ix_notifications_diagnosis_id'), 'notifications', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_scheduled_at'), 'notifications', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('users', sa.Column('fcm_token', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fcm_token')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_scheduled_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_diagnosis_id'), table_name='notifications')
    op.drop_index('ix_notification_user_unread', table_name='notifications')
    op.drop_index('ix_notification_pending', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('user_notification_preferences')
    # ### end Alembic commands ###
