"""add_name_http_status_confidence_flag_nullable_treatment

Revision ID: 7fe689a1829d
Revises: 4447ec11d413
Create Date: 2026-05-24 19:26:11.193896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe689a1829d'
down_revision: Union[str, None] = '4447ec11d413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('http_status_code', sa.Integer(), nullable=True))
    op.add_column('diagnosis_history', sa.Column('is_confidence_flag', sa.Boolean(), nullable=True))
    op.alter_column('diagnosis_history', 'treatment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('diagnosis_history_treatment_id_fkey', 'diagnosis_history', type_='foreignkey')
    op.create_foreign_key(None, 'diagnosis_history', 'treatment_records', ['treatment_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_constraint(None, 'diagnosis_history', type_='foreignkey')
    op.create_foreign_key('diagnosis_history_treatment_id_fkey', 'diagnosis_history', 'treatment_records', ['treatment_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('diagnosis_history', 'treatment_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('diagnosis_history', 'is_confidence_flag')
    op.drop_column('audit_logs', 'http_status_code')
    # ### end Alembic commands ###
