"""add_refresh_token_column_to_users

Revision ID: a84bf63be463
Revises: 19c3fff5a279
Create Date: 2026-06-22 12:01:26.132225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a84bf63be463'
down_revision: Union[str, None] = '19c3fff5a279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('refresh_token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_expiry')
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###
