"""initial_clean_schema

Revision ID: dab6b8d6950e
Revises: 
Create Date: 2026-06-17 20:45:12.756084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dab6b8d6950e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disease_name', sa.String(length=100), nullable=False),
    sa.Column('crop_type', sa.String(length=20), nullable=False),
    sa.Column('severity_level', sa.String(length=10), nullable=False),
    sa.Column('pesticide_name', sa.String(length=100), nullable=False),
    sa.Column('dosage_mild', sa.String(length=100), nullable=False),
    sa.Column('dosage_moderate', sa.String(length=100), nullable=False),
    sa.Column('dosage_severe', sa.String(length=100), nullable=False),
    sa.Column('application_timing', sa.Text(), nullable=False),
    sa.Column('safety_instructions', sa.Text(), nullable=False),
    sa.Column('pre_harvest_interval_days', sa.Integer(), nullable=False),
    sa.Column('source_reference', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_disease_crop_severity', 'treatment_records', ['disease_name', 'crop_type', 'severity_level'], unique=True)
    op.create_index(op.f('ix_treatment_records_disease_name'), 'treatment_records', ['disease_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('language_pref', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('diagnosis_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('disease_label', sa.String(length=100), nullable=False),
    sa.Column('crop_type', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=True),
    sa.Column('treatment_id', sa.UUID(), nullable=True),
    sa.Column('image_blur_score', sa.Float(), nullable=False),
    sa.Column('image_brightness', sa.Float(), nullable=False),
    sa.Column('quality_passed', sa.Boolean(), nullable=False),
    sa.Column('low_confidence_warning', sa.Boolean(), nullable=False),
    sa.Column('diagnosed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatment_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_history_diagnosed_at'), 'diagnosis_history', ['diagnosed_at'], unique=False)
    op.create_index(op.f('ix_diagnosis_history_disease_label'), 'diagnosis_history', ['disease_label'], unique=False)
    op.create_index(op.f('ix_diagnosis_history_treatment_id'), 'diagnosis_history', ['treatment_id'], unique=False)
    op.create_index(op.f('ix_diagnosis_history_user_id'), 'diagnosis_history', ['user_id'], unique=False)
    op.create_index('ix_user_diagnosed_at', 'diagnosis_history', ['user_id', 'diagnosed_at'], unique=False)
    op.create_table('treatment_translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('treatment_record_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=2), nullable=False),
    sa.Column('disease_name_translated', sa.String(length=200), nullable=False),
    sa.Column('treatment_instructions_translated', sa.Text(), nullable=False),
    sa.Column('safety_warnings_translated', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['treatment_record_id'], ['treatment_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_treatment_lang', 'treatment_translations', ['treatment_record_id', 'language_code'], unique=True)
    op.create_index(op.f('ix_treatment_translations_treatment_record_id'), 'treatment_translations', ['treatment_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_treatment_translations_treatment_record_id'), table_name='treatment_translations')
    op.drop_index('ix_treatment_lang', table_name='treatment_translations')
    op.drop_table('treatment_translations')
    op.drop_index('ix_user_diagnosed_at', table_name='diagnosis_history')
    op.drop_index(op.f('ix_diagnosis_history_user_id'), table_name='diagnosis_history')
    op.drop_index(op.f('ix_diagnosis_history_treatment_id'), table_name='diagnosis_history')
    op.drop_index(op.f('ix_diagnosis_history_disease_label'), table_name='diagnosis_history')
    op.drop_index(op.f('ix_diagnosis_history_diagnosed_at'), table_name='diagnosis_history')
    op.drop_table('diagnosis_history')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_treatment_records_disease_name'), table_name='treatment_records')
    op.drop_index('ix_disease_crop_severity', table_name='treatment_records')
    op.drop_table('treatment_records')
    # ### end Alembic commands ###
